### ISSUE TITLE
Sidebar link color not WS

### ISSUE THREAD

**Issue by bergeson** [fsoe-asu/fultonSchoolsDiviTheme#26]
Discovered this weekend that the sidebar link color on Poly is not consistent with the theme or with the Theme Customizer. Sidebar links are grey with maroon dotted underline decoration, and they rollover to the standard Divi blue link color. I checked the theme settings and do not see a place to override the color for the sidebar links.
![sidebarlinkexample](https://cloud.githubusercontent.com/assets/16543935/22425256/dc01e47c-e6bf-11e6-8c42-026316e58b90.png)

Example page: http://poly.engineering.asu.edu/aviation/air-transportation-management-bs/

**Comment by SteveRyan-ASU** [comment]
Tracking down this "feature" a little better. Within Divi, there's a Theme Option in the Customizer module that sets a "theme accent color" by default. The menu location is pictured below. 

![2017-01-30_10-19-55](https://cloud.githubusercontent.com/assets/2085753/22433715/89f18e64-e6d6-11e6-8f06-19910456b87f.png)

Changing that option sets a bunch of things in motion which all wind up in line 89 of the rendered HTML page when viewing it in the browser. That rule is as follows:

````css
#et_search_icon:hover, .mobile_menu_bar:before, .mobile_menu_bar:after,
 .et_toggle_slide_menu:after, .et-social-icon a:hover, .et_pb_sum, .et_pb_pricing li a,
 .et_pb_pricing_table_button, .et_overlay:before, .entry-summary p.price ins,
.woocommerce div.product span.price, .woocommerce-page div.product span.price, 
.woocommerce #content div.product span.price, 
.woocommerce-page #content div.product span.price,
.woocommerce div.product p.price, .woocommerce-page div.product p.price, 
.woocommerce #content div.product p.price, .woocommerce-page #content div.product p.price, 
.et_pb_member_social_links a:hover, .woocommerce .star-rating span:before, 
.woocommerce-page .star-rating span:before, .et_pb_widget li a:hover, .et_pb_filterable_portfolio .et_pb_portfolio_filters li a.active, .et_pb_filterable_portfolio 
.et_pb_portofolio_pagination ul li a.active, .et_pb_gallery .et_pb_gallery_pagination ul li a.active, 
.wp-pagenavi span.current, .wp-pagenavi a:hover, .nav-single a, .posted_in a {
    color: #8c1d40; //your theme option color here
}
````

Specifically for this issue, I  should be able to write a more specific CSS rule that overwrites the single rule that gets dragged through the mud by the theme. That rule (for reference, again) is: `.et_pb_widget li a:hover`
